// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("filewatch")
	ScopeName = "github.com/olandr/opentelemetry-collector-contrib/receiver/filewatch"
)

const (
	LogsStability = component.StabilityLevelDevelopment
)
